### ISSUE TITLE
Implement autofill program

### ISSUE THREAD

**Issue by veli-m-andirin** [gslab-econ/gslab_stata#10]
In this issue we'll bring the autofill program we've written in Protests to this repo.

**Comment by veli-m-andirin** [comment]
@jmshapir, can you please give me write access to this repo for pushing my changes?

**Comment by jmshapir** [comment]
@veli-m-andirin done, use it wisely, thanks!

**Comment by veli-m-andirin** [comment]
Continues in #11.

**Comment by veli-m-andirin** [comment]
Summary: In this issue we added a program to facilitate autofilling. Changes were merged into master in 91d2c3b. Final state of the issue branch is [here](https://github.com/gslab-econ/gslab_stata/tree/19f7734845917f2d6ad5fe188b8546957141bf55).
