### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by M-R-Sullivan** [gslab-econ/gslab_stata#3]
Goal: to clarify how users install the repository's code libraries.

**Comment by M-R-Sullivan** [comment]
@gentzkow - I ended up making the repo public and adding instructions to install its packages from the Stata console, which was fairly straightforward to do. Let me know if you have any additional thoughts. 

This thread will continue at #4, which I opened up for this issue's PR.

**Comment by lboxell** [comment]
Pull request: https://github.com/gslab-econ/gslab_stata/pull/4

Summary:
 - Added installation instructions to make downloading stata packages easier.
 - Removed non-gslab ado files.
 - Added license.
 - Made public.
