### ISSUE TITLE
Bug: Installation instructions fail if installing for the first time

### ISSUE THREAD

**Issue by mirajshah** [gslab-econ/gslab_stata#5]
Hi, I am running Stata 14.2 on Windows and tried to follow the instructions to install `gslab_misc` given in the corresponding [readme.md file](https://github.com/gslab-econ/gslab_stata/blob/master/gslab_misc/readme.md). I got the following error:

```
. net uninstall benchmark 
package not found
r(111);
```

It looks like `net uninstall` fails when the package does not exist. Might it be better to just have a series of `net install <package>, replace` commands instead of a series of `net uninstall`, `net install` command pairs? Thanks

**Comment by arosenbe** [comment]
Thanks @mirajshah, good suggestion. We'll implement in #6.

**Comment by arosenbe** [comment]
PR passed by @stanfordquan at #6. Rewrites
```stata
net uninstall a_package
net install a_package
```
as 

```stata
net install a_package, replace
```
